name: Android SauceLabs My Demo App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ios/**'
      - '__tests__/**'
      - 'docs/**'
      - '**.md'
      - '**/ios.yml'
defaults:
  run:
    working-directory: android
jobs:
  ReleaseBuild:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
        # Fix for 'Android Studio error "Installed Build Tools revision 31/32.0.0 is corrupted"'
      - name: Fix BuildTools
        run: |
          ln -s ${ANDROID_HOME}/build-tools/32.0.0/d8 ${ANDROID_HOME}/build-tools/32.0.0/dx
          ln -s ${ANDROID_HOME}/build-tools/32.0.0/lib/d8.jar ${ANDROID_HOME}/build-tools/32.0.0/lib/dx.jar
      - name: Build Android Release
        run: |
          yarn android.release
      - name: Detect App Name
        run: |
          echo "APP_NAME=${basename android/app/build/outputs/apk/release/*.apk}" >> $GITHUB_ENV
        shell: bash
      - name: Archive Apps
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.APP_NAME}}
          path: '**/app/build/outputs/apk/release/**/*.apk'
